export const CAMPUS_CODES = {
  'Atanur Oğuz Kampüsü': 'AO',
  'Acıbadem Kampüsü': 'AB',
  'Kemal Atatürk Kampüsü': 'KA',
  'Uluğbey Kampüsü': 'UB',
  'Kaşgarlı Mahmut Kampüsü': 'KM',
  'Antalya Kampüsü (Konyaaltı)': 'AK',
  'İzmir Kampüsü': 'İO',
  'Semiha Şakir Kampüsü': 'SS',
  'Bilge Kağan Kampüsü': 'BK',
  'Antalya Kampüsü (Lara)': 'AL',
  'Ankara Kampüsü': 'AN',
  'Genel Müdürlük': 'GM',
  'Belde Kampüsü': 'BE',
};

export const TYPE_BRANDS = {
  Laptop: ['Lenovo', 'HP', 'Dell', 'Apple', 'Asus', 'Casper', 'Diğer'],
  'Masaüstü (PC)': ['Lenovo', 'HP', 'Dell', 'Asus', 'Casper', 'Apple', 'Diğer'],
  'All in One PC': ['Lenovo', 'HP', 'Dell', 'Asus', 'Casper', 'Apple', 'Diğer'],
  Tablet: ['Apple', 'Samsung', 'Lenovo', 'Diğer'],
  Monitör: [
    'Samsung',
    'Philips',
    'ViewSonic',
    'AOC',
    'Lenovo',
    'HP',
    'Dell',
    'Asus',
    'Diğer',
  ],
  'Klavye ve Mouse Seti': [
    'Logitech',
    'A4Tech',
    'Everest',
    'Lenovo',
    'HP',
    'Dell',
    'Diğer',
  ],
  Mouse: [
    'Logitech',
    'A4Tech',
    'Everest',
    'Apple',
    'Lenovo',
    'HP',
    'Dell',
    'Asus',
    'Diğer',
  ],
  Klavye: [
    'Logitech',
    'A4Tech',
    'Everest',
    'Apple',
    'Lenovo',
    'HP',
    'Dell',
    'Asus',
    'Diğer',
  ],
  Webcam: ['Logitech', 'A4Tech', 'Diğer'],
  'Hard Drive': ['Samsung', 'Diğer'],
  Diğer: ['Diğer'],
};

export const BRANDS_MODELS = {
  Lenovo: [
    'ThinkPad E15',
    'ThinkPad E14',
    'V15',
    'IdeaPad',
    'ThinkCentre',
    'All in One (AIO)',
    'Diğer',
  ],
  HP: [
    'ProBook',
    'EliteBook',
    'Pavilion',
    '250 G8',
    'ProDesk',
    'All in One (AIO)',
    'Victus',
    'Diğer',
  ],
  Dell: [
    'Latitude',
    'Vostro',
    'OptiPlex',
    'Inspiron',
    'All in One (AIO)',
    'Diğer',
  ],
  Apple: ['MacBook Air', 'MacBook Pro', 'iMac', 'Mac mini', 'Diğer'],
  Asus: ['ZenBook', 'VivoBook', 'ExpertBook', 'All in One (AIO)', 'Diğer'],
  Casper: ['Nirvana', 'Excalibur', 'All in One (AIO)', 'Diğer'],
  Logitech: [
    'MK220 (Set)',
    'MK235 (Set)',
    'MK240 (Set)',
    'MK270 (Set)',
    'M170 (Mouse)',
    'M185 (Mouse)',
    'M220 (Mouse)',
    'Standart Klavye',
    'Diğer',
  ],
  A4Tech: ['Standart Mouse', 'Standart Klavye', 'Diğer'],
  Everest: ['Standart Mouse', 'Standart Klavye', 'Diğer'],
  Samsung: ['Standart Monitör', 'Diğer'],
  Philips: ['Standart Monitör', 'Diğer'],
  ViewSonic: ['Standart Monitör', 'Diğer'],
  AOC: ['Standart Monitör', 'Diğer'],
  Diğer: ['Standart', 'Diğer'],
};
